kind: pipeline
name: managementapi
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: managementapi
    when:
      branch:
        - token
    image: docker:dind
    environment:
      IMAGE: managementapi
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build -f ./src/Token.ManagementApi.Host/Dockerfile -t managementapi .
      - docker stop managementapi && docker rm managementapi
      - docker run -d --network token -v /etc/localtime:/etc/localtime --name managementapi managementapi:latest

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
