kind: pipeline
name: authorization
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: managementapi:dev
    image: linuxserver/docker-compose
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build -f ./src/Token.ManagementApi.Host/Dockerfile -t registry.cn-shenzhen.aliyuncs.com/tokengo/managementapi:dev .
      - docker-compose down && docker-compose up -d
      
volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock