version: '3.7'

services:
  managementapi:
    image: registry.cn-shenzhen.aliyuncs.com/tokengo/managementapi:dev
    volumes:
      - /etc/localtime:/etc/localtime
      - /managementapi/logs:/app/log
    container_name: managementapi
    restart: always
    networks:
      - token

networks:
  token:
    external: true

    