// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Token.Management.EntityFrameworkCore.EntityFrameworkCore;

#nullable disable

namespace Token.Management.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(TokenDbContext))]
    [Migration("20220607154305_CreateData")]
    partial class CreateData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Token.Management.Domain.Management.AccessFunction.MenuRoleFunction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("UserInfoId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserInfoId");

                    b.ToTable("token_menu_role_function", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f808acc8-a746-46ee-b1be-97d7decd254c"),
                            CreationTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MenuId = new Guid("5de1db7f-d249-43f5-9230-3833544b87b1"),
                            RoleId = new Guid("5610d63a-183d-47a4-ab82-5d308ac15b8d")
                        },
                        new
                        {
                            Id = new Guid("3522f2b4-d35b-4913-8425-7c5e3006aa21"),
                            CreationTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MenuId = new Guid("da57bf0e-6c03-4ef4-a2ac-0cf576c3b0b5"),
                            RoleId = new Guid("5610d63a-183d-47a4-ab82-5d308ac15b8d")
                        },
                        new
                        {
                            Id = new Guid("d879ae65-3f52-4870-bf6e-83c94dc66bb0"),
                            CreationTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MenuId = new Guid("fafbe9c5-6b41-4981-8ebc-f30917b32c87"),
                            RoleId = new Guid("5610d63a-183d-47a4-ab82-5d308ac15b8d")
                        },
                        new
                        {
                            Id = new Guid("f51c106b-2e88-4739-b259-1c97d380f6f9"),
                            CreationTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MenuId = new Guid("5b3c39c8-f212-4105-85ae-cf34422d6026"),
                            RoleId = new Guid("5610d63a-183d-47a4-ab82-5d308ac15b8d")
                        },
                        new
                        {
                            Id = new Guid("07109f16-fa61-41c7-a396-1ff420c46da7"),
                            CreationTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MenuId = new Guid("4ac2f4d0-990b-4be1-9409-46fe034b2aa4"),
                            RoleId = new Guid("5610d63a-183d-47a4-ab82-5d308ac15b8d")
                        },
                        new
                        {
                            Id = new Guid("1ab255af-c439-425c-b2a8-767bd3a801f7"),
                            CreationTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MenuId = new Guid("05abe233-4252-499e-b91b-5721d784ab36"),
                            RoleId = new Guid("5610d63a-183d-47a4-ab82-5d308ac15b8d")
                        },
                        new
                        {
                            Id = new Guid("d8aac5ab-557e-4d1d-9a86-7d9a9d0e6cef"),
                            CreationTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MenuId = new Guid("fbfdfdb4-69ea-46d9-8740-d62ffb22f87d"),
                            RoleId = new Guid("5610d63a-183d-47a4-ab82-5d308ac15b8d")
                        });
                });

            modelBuilder.Entity("Token.Management.Domain.Management.AccessFunction.UserDepartmentFunction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("UserInfoId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Id");

                    b.HasIndex("UserInfoId");

                    b.ToTable("token_user_department_function", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c320a3d6-40b8-48cc-ab80-74a4a7f120cd"),
                            CreationTime = new DateTime(2022, 6, 7, 23, 43, 5, 390, DateTimeKind.Local).AddTicks(6630),
                            DepartmentId = new Guid("96017ff8-52cd-4d85-b7b8-474b1bf51de0"),
                            IsDeleted = false,
                            UserInfoId = new Guid("665203a9-6328-4358-a1f2-6588802c393b")
                        });
                });

            modelBuilder.Entity("Token.Management.Domain.Management.AccessFunction.UserRoleFunction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserInfoId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserInfoId");

                    b.ToTable("token_user_role_function", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6ee0907d-bb79-4b6c-9c96-f6d8b3f5a958"),
                            CreationTime = new DateTime(2022, 6, 7, 23, 43, 5, 390, DateTimeKind.Local).AddTicks(6630),
                            IsDeleted = false,
                            RoleId = new Guid("5610d63a-183d-47a4-ab82-5d308ac15b8d"),
                            UserInfoId = new Guid("665203a9-6328-4358-a1f2-6588802c393b")
                        });
                });

            modelBuilder.Entity("Token.Management.Domain.Management.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Describe")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Logo")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("token_company", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5e69bd0f-1b25-459a-b5cb-bb7086821d1c"),
                            Code = "wr",
                            CreationTime = new DateTime(2022, 6, 7, 23, 43, 5, 390, DateTimeKind.Local).AddTicks(6630),
                            Describe = "微软（Microsoft）是一家 美国 跨国科技企业，由 比尔·盖茨 和 保罗·艾伦 于1975年4月4日创立。 公司总部设立在 华盛顿州 雷德蒙德 （Redmond，邻近 西雅图 ），以 研发 、 制造 、 授权 和提供广泛的 电脑软件 服务业务为主 。",
                            IsDeleted = false,
                            Name = "Microsoft"
                        });
                });

            modelBuilder.Entity("Token.Management.Domain.Management.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("UserInfoId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Id");

                    b.HasIndex("UserInfoId");

                    b.ToTable("token_department", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("96017ff8-52cd-4d85-b7b8-474b1bf51de0"),
                            Code = "cs",
                            CompanyId = new Guid("5e69bd0f-1b25-459a-b5cb-bb7086821d1c"),
                            CreationTime = new DateTime(2022, 6, 7, 23, 43, 5, 390, DateTimeKind.Local).AddTicks(6630),
                            Index = 0,
                            IsDeleted = false,
                            Name = "测试部门"
                        });
                });

            modelBuilder.Entity("Token.Management.Domain.Management.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Component")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Icon")
                        .HasColumnType("longtext");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Path")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("token_menu", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5de1db7f-d249-43f5-9230-3833544b87b1"),
                            Component = "Home",
                            CreationTime = new DateTime(2022, 6, 7, 23, 43, 5, 390, DateTimeKind.Local).AddTicks(6630),
                            Index = 0,
                            IsDeleted = false,
                            Name = "首页",
                            Path = "/home/index",
                            Title = "首页"
                        },
                        new
                        {
                            Id = new Guid("da57bf0e-6c03-4ef4-a2ac-0cf576c3b0b5"),
                            Component = "User",
                            CreationTime = new DateTime(2022, 6, 7, 23, 43, 5, 390, DateTimeKind.Local).AddTicks(6630),
                            Index = 1,
                            IsDeleted = false,
                            Name = "用户管理",
                            Path = "/user/index",
                            Title = "用户管理"
                        },
                        new
                        {
                            Id = new Guid("fafbe9c5-6b41-4981-8ebc-f30917b32c87"),
                            Component = "System",
                            CreationTime = new DateTime(2022, 6, 7, 23, 43, 5, 390, DateTimeKind.Local).AddTicks(6630),
                            Index = 2,
                            IsDeleted = false,
                            Name = "系统配置",
                            Path = "/system/index",
                            Title = "系统配置"
                        },
                        new
                        {
                            Id = new Guid("5b3c39c8-f212-4105-85ae-cf34422d6026"),
                            Component = "Work",
                            CreationTime = new DateTime(2022, 6, 7, 23, 43, 5, 390, DateTimeKind.Local).AddTicks(6630),
                            Index = 3,
                            IsDeleted = false,
                            Name = "工作",
                            Path = "/Work/index",
                            Title = "工作"
                        },
                        new
                        {
                            Id = new Guid("4ac2f4d0-990b-4be1-9409-46fe034b2aa4"),
                            Component = "UserConfig",
                            CreationTime = new DateTime(2022, 6, 7, 23, 43, 5, 390, DateTimeKind.Local).AddTicks(6630),
                            Index = 1,
                            IsDeleted = false,
                            Name = "用户权限配置",
                            ParentId = new Guid("fafbe9c5-6b41-4981-8ebc-f30917b32c87"),
                            Path = "/system/userConfig/index",
                            Title = "用户权限配置"
                        },
                        new
                        {
                            Id = new Guid("05abe233-4252-499e-b91b-5721d784ab36"),
                            Component = "RoleConfig",
                            CreationTime = new DateTime(2022, 6, 7, 23, 43, 5, 390, DateTimeKind.Local).AddTicks(6630),
                            Index = 0,
                            IsDeleted = false,
                            Name = "角色配置",
                            ParentId = new Guid("fafbe9c5-6b41-4981-8ebc-f30917b32c87"),
                            Path = "/system/roleConfig/index",
                            Title = "角色配置"
                        },
                        new
                        {
                            Id = new Guid("fbfdfdb4-69ea-46d9-8740-d62ffb22f87d"),
                            Component = "WorkConfig",
                            CreationTime = new DateTime(2022, 6, 7, 23, 43, 5, 390, DateTimeKind.Local).AddTicks(6630),
                            Index = 2,
                            IsDeleted = false,
                            Name = "工作流配置",
                            ParentId = new Guid("fafbe9c5-6b41-4981-8ebc-f30917b32c87"),
                            Path = "/system/workConfig/index",
                            Title = "工作流配置"
                        });
                });

            modelBuilder.Entity("Token.Management.Domain.Management.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .HasColumnType("longtext")
                        .HasComment("角色编号");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Index")
                        .HasColumnType("int")
                        .HasComment("序号");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasComment("角色名称");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("char(36)")
                        .HasComment("父节点");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext")
                        .HasComment("备注");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("token_role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5610d63a-183d-47a4-ab82-5d308ac15b8d"),
                            Code = "admin",
                            CreationTime = new DateTime(2022, 6, 7, 23, 43, 5, 390, DateTimeKind.Local).AddTicks(6630),
                            Index = 0,
                            IsDeleted = false,
                            Name = "管理员",
                            Remark = "系统管理员"
                        });
                });

            modelBuilder.Entity("Token.Management.Domain.SystemService.SystemMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsCheck")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<int>("WorkFormCode")
                        .HasColumnType("int");

                    b.Property<Guid?>("WorkFormId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("token_system_message", (string)null);
                });

            modelBuilder.Entity("Token.Management.Domain.Users.UserInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EMail")
                        .HasColumnType("longtext")
                        .HasComment("邮箱");

                    b.Property<string>("HeadPortraits")
                        .HasColumnType("longtext")
                        .HasComment("头像");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<long?>("MobileNumber")
                        .HasMaxLength(11)
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasComment("用户昵称");

                    b.Property<string>("Password")
                        .HasColumnType("longtext")
                        .HasComment("密码");

                    b.Property<int>("Sex")
                        .HasColumnType("int")
                        .HasComment("性别");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasComment("状态");

                    b.Property<string>("WXOpenId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("token_user_info", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("665203a9-6328-4358-a1f2-6588802c393b"),
                            AccountNumber = "admin",
                            CreationTime = new DateTime(2022, 6, 7, 23, 43, 5, 390, DateTimeKind.Local).AddTicks(6630),
                            EMail = "239573049@qq.com",
                            HeadPortraits = "https://upfile2.asqql.com/upfile/hdimg/wmtp/wmtp/2018-07/08/18_7_8_16_10_08yoqapqci.jpg",
                            IsDeleted = false,
                            MobileNumber = 13049809673L,
                            Name = "管理员",
                            Password = "349843DE4F81CDE9456ADEACACE77ECF8DA4197169214575",
                            Sex = 1,
                            Status = 0
                        });
                });

            modelBuilder.Entity("Token.Management.Domain.WorkContent.WorkDemoMain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("SubmitTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("WorkFlowNodeStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("token_work_demo_main", (string)null);
                });

            modelBuilder.Entity("Token.Management.Domain.WorkFlow.WorkflowApprovalRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WorkflowNodeTemplateId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("WorkflowNodeTemplateId");

                    b.ToTable("token_workflow_approval_role", (string)null);
                });

            modelBuilder.Entity("Token.Management.Domain.WorkFlow.WorkflowApprovers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("UserInfoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.Property<int>("WorkFlowFormCode")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("WorkflowInstanceId");

                    b.ToTable("token_workflow_approvers", (string)null);
                });

            modelBuilder.Entity("Token.Management.Domain.WorkFlow.WorkflowInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ArchiveDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Code")
                        .HasColumnType("longtext")
                        .HasComment("工作流实例code");

                    b.Property<string>("CurrentRoleCode")
                        .HasColumnType("longtext");

                    b.Property<bool>("HasBeenRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext")
                        .HasComment("工作流实例备注");

                    b.Property<Guid>("SponsorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SponsorName")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("SponsoredDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("WorkFlowFormCode")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkFormId")
                        .HasColumnType("char(36)");

                    b.Property<int>("WorkflowStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkflowTemplateId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("SponsorId");

                    b.HasIndex("WorkflowTemplateId");

                    b.ToTable("token_workflow_instance", (string)null);
                });

            modelBuilder.Entity("Token.Management.Domain.WorkFlow.WorkflowNodeInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("AuditDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("AuditPersonId")
                        .HasColumnType("char(36)");

                    b.Property<string>("AuditPersonName")
                        .HasColumnType("longtext");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("NextNodeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("NextTemplateNodeId")
                        .HasColumnType("char(36)");

                    b.Property<int>("NodeStatus")
                        .HasColumnType("int");

                    b.Property<Guid?>("PrevNodeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("PrevTemplateNodeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext");

                    b.Property<Guid>("TemplateNodeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("WorkflowInstanceId");

                    b.ToTable("token_workflowNode_instance", (string)null);
                });

            modelBuilder.Entity("Token.Management.Domain.WorkFlow.WorkflowNodeTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("NextNodeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("PrevNodeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext");

                    b.Property<Guid>("WorkflowTemplateId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("WorkflowTemplateId");

                    b.ToTable("token_workflow_node_template", (string)null);
                });

            modelBuilder.Entity("Token.Management.Domain.WorkFlow.WorkflowTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .HasColumnType("longtext")
                        .HasComment("工作流模板编号");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasComment("工作流模板名称");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext")
                        .HasComment("工作流模板备注");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("token_workflow_template", (string)null);
                });

            modelBuilder.Entity("Volo.Abp.Data.ExtraPropertyDictionary", b =>
                {
                    b.Property<int>("Count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("Count");

                    b.ToTable("ExtraPropertyDictionary");
                });

            modelBuilder.Entity("Token.Management.Domain.Management.AccessFunction.MenuRoleFunction", b =>
                {
                    b.HasOne("Token.Management.Domain.Management.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Token.Management.Domain.Management.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Token.Management.Domain.Users.UserInfo", null)
                        .WithMany("MenuRoleFunction")
                        .HasForeignKey("UserInfoId");

                    b.Navigation("Menu");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Token.Management.Domain.Management.AccessFunction.UserDepartmentFunction", b =>
                {
                    b.HasOne("Token.Management.Domain.Management.Department", "Department")
                        .WithMany("UserDepartmentFunction")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Token.Management.Domain.Users.UserInfo", "UserInfo")
                        .WithMany("UserDepartmentFunction")
                        .HasForeignKey("UserInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("Token.Management.Domain.Management.AccessFunction.UserRoleFunction", b =>
                {
                    b.HasOne("Token.Management.Domain.Management.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Token.Management.Domain.Users.UserInfo", "UserInfo")
                        .WithMany("UserRoleFunction")
                        .HasForeignKey("UserInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("Token.Management.Domain.Management.Department", b =>
                {
                    b.HasOne("Token.Management.Domain.Management.Company", "Company")
                        .WithMany("Department")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Token.Management.Domain.Users.UserInfo", null)
                        .WithMany("Department")
                        .HasForeignKey("UserInfoId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Token.Management.Domain.WorkFlow.WorkflowApprovalRole", b =>
                {
                    b.HasOne("Token.Management.Domain.Management.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Token.Management.Domain.WorkFlow.WorkflowNodeTemplate", "WorkflowNodeTemplate")
                        .WithMany("WorkflowApprovalRole")
                        .HasForeignKey("WorkflowNodeTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("WorkflowNodeTemplate");
                });

            modelBuilder.Entity("Token.Management.Domain.WorkFlow.WorkflowApprovers", b =>
                {
                    b.HasOne("Token.Management.Domain.WorkFlow.WorkflowInstance", "WorkflowInstance")
                        .WithMany("WorkflowApprovers")
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowInstance");
                });

            modelBuilder.Entity("Token.Management.Domain.WorkFlow.WorkflowInstance", b =>
                {
                    b.HasOne("Token.Management.Domain.Users.UserInfo", "Sponsor")
                        .WithMany()
                        .HasForeignKey("SponsorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Token.Management.Domain.WorkFlow.WorkflowTemplate", "WorkflowTemplate")
                        .WithMany("WorkflowInstance")
                        .HasForeignKey("WorkflowTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sponsor");

                    b.Navigation("WorkflowTemplate");
                });

            modelBuilder.Entity("Token.Management.Domain.WorkFlow.WorkflowNodeInstance", b =>
                {
                    b.HasOne("Token.Management.Domain.WorkFlow.WorkflowInstance", "WorkflowInstance")
                        .WithMany("WorkflowNodeInstances")
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowInstance");
                });

            modelBuilder.Entity("Token.Management.Domain.WorkFlow.WorkflowNodeTemplate", b =>
                {
                    b.HasOne("Token.Management.Domain.WorkFlow.WorkflowTemplate", "WorkflowTemplate")
                        .WithMany("WorkflowNodeTemplate")
                        .HasForeignKey("WorkflowTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowTemplate");
                });

            modelBuilder.Entity("Token.Management.Domain.Management.Company", b =>
                {
                    b.Navigation("Department");
                });

            modelBuilder.Entity("Token.Management.Domain.Management.Department", b =>
                {
                    b.Navigation("UserDepartmentFunction");
                });

            modelBuilder.Entity("Token.Management.Domain.Users.UserInfo", b =>
                {
                    b.Navigation("Department");

                    b.Navigation("MenuRoleFunction");

                    b.Navigation("UserDepartmentFunction");

                    b.Navigation("UserRoleFunction");
                });

            modelBuilder.Entity("Token.Management.Domain.WorkFlow.WorkflowInstance", b =>
                {
                    b.Navigation("WorkflowApprovers");

                    b.Navigation("WorkflowNodeInstances");
                });

            modelBuilder.Entity("Token.Management.Domain.WorkFlow.WorkflowNodeTemplate", b =>
                {
                    b.Navigation("WorkflowApprovalRole");
                });

            modelBuilder.Entity("Token.Management.Domain.WorkFlow.WorkflowTemplate", b =>
                {
                    b.Navigation("WorkflowInstance");

                    b.Navigation("WorkflowNodeTemplate");
                });
#pragma warning restore 612, 618
        }
    }
}
